"""FakeLiepinDriver：World JSON 剧本驱动的 LiepinDriver 完整实现（mock 模式）。

确定性：PNG/PDF 字节由 (seed) 纯函数生成——同一剧本同一 tick 得到完全
相同的字节（可复现），不同候选人/附件得到不同字节。运行期状态（已发
消息、已打开会话）记录在实例上，不改写剧本。

异常约定（fake 的"真实感"，T9 worker 据此置任务 failed）：
未知 conversation_id 抛 ConversationNotFoundError；会话无简历 fixture 抛
NoResumeFixtureError；无已送达附件抛 NoAttachmentError。
"""

import hashlib
import struct
import zlib
from typing import Callable

from hr_workbuddy import MinimalResume

from app.world import ConversationScript, ReplyEvent, World


class ConversationNotFoundError(Exception):
    """剧本中不存在该 liepin_user_id 的会话。"""


class NoResumeFixtureError(Exception):
    """会话未配置 resume fixture（真实世界：候选人无在线简历可读）。"""


class NoAttachmentError(Exception):
    """该会话当前无已送达附件可下载。"""


def png_bytes(seed: str) -> bytes:
    """确定性最小合法 PNG（签名 + IHDR + IDAT + IEND），尺寸与像素由 seed 派生。

    RGB 真彩色，行 = filter 0 + 3×width 字节，zlib 压缩——字节级合法，
    可被任意 PNG 解码器打开；同 seed 同字节。
    """

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    digest = hashlib.sha256(seed.encode("utf-8")).digest()
    width = 64 + digest[0] % 128
    height = 64 + digest[1] % 128
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    row = b"\x00" + (digest * (3 * width // 32 + 1))[: 3 * width]
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(row * height))
        + chunk(b"IEND", b"")
    )


def pdf_bytes(seed: str) -> bytes:
    """确定性最小合法 PDF（头部 + seed 派生填充 + %%EOF；占位字节，不用于打开）。"""
    digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()
    return (
        b"%PDF-1.4\n% fake attachment generated by FakeLiepinDriver seed="
        + digest.encode("ascii")
        + b"\n"
        + (digest * 4).encode("ascii")
        + b"\n%%EOF\n"
    )


class FakeLiepinDriver:
    """CUA_DRIVER_MODE=mock 时被 worker 选用；只依赖 World 与注入时钟，无 I/O。"""

    def __init__(self, world: World, now: Callable[[], int] | None = None) -> None:
        self.world = world
        self.now = now  # 时钟注入：None = 剧本 tick（world.tick）
        self.sent_messages: list[tuple[str, str]] = []
        self.opened: set[str] = set()

    # —— 剧本查询 ——

    def _tick(self) -> int:
        return self.world.tick if self.now is None else self.now()

    def _conversation(self, candidate_liepin_id: str) -> ConversationScript:
        for conv in self.world.conversations:
            if conv.liepin_user_id == candidate_liepin_id:
                return conv
        raise ConversationNotFoundError(f"剧本中无会话 {candidate_liepin_id!r}")

    def _events(self, candidate_liepin_id: str) -> list[ReplyEvent]:
        return [
            e
            for e in self.world.visible_events(self._tick())
            if e.conversation_id == candidate_liepin_id
        ]

    # —— LiepinDriver 协议（contracts 逐字：7 方法） ——

    def check_login(self) -> bool:
        return self.world.login_state

    def list_unread_conversations(self) -> list[str]:
        return [c.liepin_user_id for c in self.world.conversations if c.unread]

    def list_recommended(self, limit: int = 5) -> list[str]:
        """M2 推荐人列表：剧本 recommended 标记的会话（顺序即列表顺序），
        最多 limit 张（与真实驱动语义对齐：可见/可读上限）。"""
        ids = [c.liepin_user_id for c in self.world.conversations if c.recommended]
        return ids[: max(1, int(limit))]

    def open_conversation(self, candidate_liepin_id: str) -> None:
        self._conversation(candidate_liepin_id)  # 未知 id 抛错
        self.opened.add(candidate_liepin_id)

    def read_online_resume(self, candidate_liepin_id: str) -> tuple[bytes, MinimalResume]:
        conv = self._conversation(candidate_liepin_id)
        if conv.resume_fixture is None:
            raise NoResumeFixtureError(
                f"会话 {candidate_liepin_id!r} 无简历 fixture（候选人无在线简历）"
            )
        fixture = self.world.resume_fixtures.get(conv.resume_fixture)
        if fixture is None:
            raise NoResumeFixtureError(
                f"剧本无 resume fixture {conv.resume_fixture!r}"
            )
        # 幂等：不读不写运行期状态，同参数同结果
        return png_bytes(seed=f"{candidate_liepin_id}:resume"), fixture.model_copy(deep=True)

    def send_message(self, candidate_liepin_id: str, text: str) -> None:
        self._conversation(candidate_liepin_id)
        self.sent_messages.append((candidate_liepin_id, text))

    def check_attachment(self, candidate_liepin_id: str) -> bool:
        self._conversation(candidate_liepin_id)
        return any(e.attachment is not None for e in self._events(candidate_liepin_id))

    def download_attachment(self, candidate_liepin_id: str) -> tuple[bytes, str]:
        self._conversation(candidate_liepin_id)
        attachments = [e for e in self._events(candidate_liepin_id) if e.attachment is not None]
        if not attachments:
            raise NoAttachmentError(f"会话 {candidate_liepin_id!r} 无已送达附件")
        spec = attachments[-1].attachment  # 最新送达的附件
        assert spec is not None  # 已过滤 attachment is not None
        # R7：返回 (字节, 文件名)——文件名来自剧本附件定义，供 worker 上传 artifact
        return pdf_bytes(seed=f"{candidate_liepin_id}:{spec.file_name}"), spec.file_name
